name: Build Image

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"
  workflow_dispatch:
  schedule:
    - cron: '35 6 * * *'

jobs:
  build-image:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    container:
      image: quay.io/podman/stable

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Build
        run: |
          podman build -t ${{ github.repository }}:$(date --iso-8601=date) .
          podman build -t ${{ github.repository }}:latest .

      - name: Push
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u $ --password-stdin
          podman push ${{ github.repository }}:$(date --iso-8601=date)
          podman push ${{ github.repository }}:latest
